function render(){const s=current();(templates[s.template]||template_c1s1)()}
function setForm(){const s=current();['title','body','support','cta','titleScale','bodyScale','titleShift','visualShift','overlay','bgZoom','showCounter'].forEach(id=>{const el=$(id);if(el.type==='checkbox')el.checked=!!s[id];else el.value=s[id]??''});$('role').textContent='תפקיד בפאנל: '+project.carousels[ci].role;$('imageHint').textContent=({c1s2:'מומלץ: צילום מקורי של ריסוס על העור.',c3s4:'כשתצלם את האב־טיפוס, העלה כאן את צילום הערכה האמיתי.',c1s1:'אופציונלי. ה־Cover עובד גם ללא תמונה.',c2s1:'בדרך כלל אין צורך בתמונה חיצונית. הדוח הוא ה־Hero.'}[s.template]||'אופציונלי. התבנית עובדת גם ללא תמונה.');renderSpecial();drawTabs();refreshImages()}
function renderSpecial(){const s=current(),box=$('specialFields');box.innerHTML='';if(['c1s4','c3s1'].includes(s.template)){box.innerHTML=`<label>הודעת Sertavo</label><textarea id="waBrand2"></textarea><label>תשובת הלקוח</label><input id="waCustomer2">`;setTimeout(()=>{$('waBrand2').value=s.waBrand||'';$('waCustomer2').value=s.waCustomer||'';$('waBrand2').oninput=e=>upd('waBrand',e.target.value);$('waCustomer2').oninput=e=>upd('waCustomer',e.target.value)},0)}else if(s.template==='c2s2'){box.innerHTML=`<div class="row"><div><label>ציון</label><input id="score2" type="number" min="0" max="100"></div><div><label>תווית</label><input id="scoreLabel2"></div></div>`;setTimeout(()=>{$('score2').value=s.score;$('scoreLabel2').value=s.scoreLabel||'';$('score2').oninput=e=>upd('score',Number(e.target.value));$('scoreLabel2').oninput=e=>upd('scoreLabel',e.target.value)},0)}else if(s.template==='c3s4'){box.innerHTML=`<label>טקסט במכסה</label><textarea id="kitLid2"></textarea>`;setTimeout(()=>{$('kitLid2').value=s.kitLid||'';$('kitLid2').oninput=e=>upd('kitLid',e.target.value)},0)}else box.innerHTML='<div class="tiny">אין שדות מיוחדים בשקופית הזו.</div>'}
function drawTabs(){const ct=$('carouselTabs');ct.innerHTML='';project.carousels.forEach((c,i)=>{const b=document.createElement('button');b.textContent=c.label;b.className=i===ci?'active':'';b.onclick=()=>{ci=i;si=0;setForm()};ct.appendChild(b)});const st=$('slideTabs');st.innerHTML='';for(let i=0;i<4;i++){const b=document.createElement('button');b.textContent=`${i+1}/4`;b.className=i===si?'active':'';b.onclick=()=>{si=i;setForm()};st.appendChild(b)}}
function upd(k,v){current()[k]=v;save();refreshImages()}
['title','body','support','cta','titleScale','bodyScale','titleShift','visualShift','overlay','bgZoom'].forEach(id=>$(id).addEventListener('input',e=>upd(id,e.target.type==='number'?Number(e.target.value):e.target.value)));$('showCounter').addEventListener('change',e=>upd('showCounter',e.target.checked));
function fileToData(file,cb){if(!file)return;const r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(file)}
$('heroFile').onchange=e=>fileToData(e.target.files[0],d=>{current().heroData=d;save();refreshImages();$('status').textContent='התמונה נטענה בהצלחה.'});
$('clearHero').onclick=()=>{current().heroData='';$('heroFile').value='';save();refreshImages()};
$('bgFile').onchange=e=>fileToData(e.target.files[0],d=>{current().bgData=d;save();refreshImages();$('status').textContent='הרקע נטען בהצלחה.'});
$('clearBg').onclick=()=>{current().bgData='';$('bgFile').value='';save();refreshImages()};
$('logoFile').onchange=e=>fileToData(e.target.files[0],d=>{project.logoData=d;save();$('logoStatus').textContent='הלוגו שהעלית פעיל';refreshImages();$('status').textContent='הלוגו הוחלף בהצלחה.'});
$('restoreLogo').onclick=()=>{project.logoData=BUILTIN_LOGO;save();$('logoStatus').textContent='הלוגו המעודכן מובנה במחולל';refreshImages()};
function blobP(){return new Promise(res=>cv.toBlob(res,'image/png',1))}
$('download').onclick=async()=>{const b=await blobP(),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`Sertavo_C${ci+1}_S${si+1}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000)};
$('share').onclick=async()=>{const b=await blobP(),f=new File([b],`Sertavo_C${ci+1}_S${si+1}.png`,{type:'image/png'});try{if(navigator.canShare?.({files:[f]})){await navigator.share({files:[f],title:'Sertavo'});$('status').textContent='נפתח תפריט השיתוף.'}else $('download').click()}catch(e){if(e.name!=='AbortError')$('download').click()}};
$('saveProject').onclick=()=>{const blob=new Blob([JSON.stringify(project)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Sertavo_Instagram_Project_v1.2.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000)};
$('loadProject').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(!p.carousels)throw 0;project=p;save();setForm();$('status').textContent='הפרויקט נטען.'}catch(err){$('status').textContent='קובץ פרויקט לא תקין.'}};r.readAsText(f)};
$('resetSlide').onclick=()=>{project.carousels[ci].slides[si]=deepClone(DEFAULTS[ci].slides[si]);save();setForm()};
$('resetAll').onclick=()=>{if(confirm('לאפס את כל 12 השקופיות?')){project={carousels:deepClone(DEFAULTS),logoData:BUILTIN_LOGO};save();setForm()}};
$('fullPreview').onclick=()=>{full=!full;$('stage').classList.toggle('fullMode',full);$('fullPreview').textContent=full?'חזור לעריכה':'תצוגה מלאה'};
const qs=new URLSearchParams(location.search);if(qs.has('c'))ci=Math.max(0,Math.min(2,Number(qs.get('c'))-1));if(qs.has('s'))si=Math.max(0,Math.min(3,Number(qs.get('s'))-1));
setForm();